name: Github Action AWS EC2 Terraform Ansible nginx
on:
  workflow_dispatch:
jobs:
  AWS-Crendentials:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: "Configure AWS Credentials" #Action for GitHub Actions
  # You may pin to the exact commit or the version.
  # uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        # AWS Region, e.g. us-east-2
        aws-region: eu-central-1
        # AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS Secret Access Key. Required if aws-access-key-id is provided.
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS Session Token.
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        # Use the web identity token file from the provided file system path in order to assume an IAM role using a web identity, e.g. from within an Amazon EKS worker node.

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Use Terraform
      run: |
          terraform -chdir=terraform/ init
          terraform -chdir=terraform/ apply -auto-approve
          ls -l
          ls -l ansible/
          cat ansible/inventory
  
